name: Build OS

# è§¦å‘æ¡ä»¶ï¼šå½“åˆ›å»ºtagæ—¶
on:
  push:
    tags:
      - 'v*'  # åŒ¹é… v1.0.0, v2.0.1 ç­‰æ ¼å¼çš„tag
      - '*'   # æˆ–åŒ¹é…æ‰€æœ‰tag
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Compile
      - name: Build project in Docker container
        run: |
          chmod -R 777 gos-live
          set -Eeuo pipefail
          docker run --rm --privileged \
            -v ${{ github.workspace }}/gos-live:/workspace \
            -v /etc/timezone:/etc/timezone \
            -w /workspace \
            debian:bookworm \
            /bin/bash -c "/workspace/local/scripts/AutoCompile.sh"

      # Upload
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GadroOS-Arifacts-${{ github.ref_name }}
          path: |
            gos-live/live-image-amd64.hybrid.iso
            gos-live/live-image-amd64.packages
            gos-live/live-image-amd64.files
            gos-live/live-image-amd64.contents
            gos-live/build.log
          retention-days: 5
      # è‡ªåŠ¨å‘å¸ƒ Beta Release
      - name: Create GitHub Release (beta)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Beta Release ${{ github.ref_name }}"
          body: |
            ğŸš€ è‡ªåŠ¨æ„å»ºçš„ Beta ç‰ˆæœ¬  
            - ISO: live-image-amd64.hybrid.iso  
          prerelease: true
          files: |
            gos-live/live-image-amd64.hybrid.iso
            gos-live/live-image-amd64.packages
            gos-live/live-image-amd64.files
            gos-live/live-image-amd64.contents
            gos-live/build.log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
